const menus = [
  { icon: 'photo-o', name: '账户总览', to: '', type: 'search', action: true, top: false },
  { icon: 'photo-o', name: '收支明细', to: '', type: 'search', action: true, top: false },
  { icon: 'photo-o', name: '我的账本', to: '', type: 'search', action: true, top: false },
  { icon: 'photo-o', name: '交易查询', to: '', type: 'search', action: true, top: false },
  { icon: 'photo-o', name: '朝朝盈', to: '', type: 'assets', action: true, top: false },
  { icon: 'photo-o', name: '摩羯智投', to: '', type: 'assets', action: true, top: false },
  { icon: 'photo-o', name: '理财产品', to: '', type: 'assets', action: true, top: false },
  { icon: 'photo-o', name: '基金', to: '', type: 'assets', action: true, top: false },
  { icon: 'photo-o', name: '私享专区', to: '', type: 'assets', action: true, top: false },
  { icon: 'photo-o', name: '存款', to: '', type: 'assets', action: false, top: false },
  { icon: 'photo-o', name: '保险', to: '', type: 'assets', action: false, top: false },
  { icon: 'photo-o', name: '黄金', to: '', type: 'assets', action: false, top: false },
  { icon: 'photo-o', name: '招财盈', to: '', type: 'assets', action: false, top: false },
  { icon: 'photo-o', name: '国债', to: '', type: 'assets', action: false, top: false },
  { icon: 'photo-o', name: '银证期转账', to: '', type: 'assets', action: false, top: false },
  { icon: 'photo-o', name: '私募', to: '', type: 'assets', action: false, top: false },
  { icon: 'photo-o', name: '财富体验', to: '', type: 'assets', action: false, top: false },
  { icon: 'photo-o', name: '风险评估', to: '', type: 'assets', action: false, top: false },
  { icon: 'photo-o', name: '持仓收益', to: '', type: 'assets', action: false, top: false },
  { icon: 'photo-o', name: '双币存款', to: '', type: 'assets', action: false, top: false },
  { icon: 'photo-o', name: '招银汇金', to: '', type: 'assets', action: false, top: false },
  { icon: 'photo-o', name: '债券', to: '', type: 'assets', action: false, top: false },
  { icon: 'photo-o', name: '转账', to: '', type: 'wealth', action: false, top: false },
  { icon: 'photo-o', name: '他行卡转入', to: '', type: 'wealth', action: false, top: false },
  { icon: 'photo-o', name: '他行卡查询', to: '', type: 'wealth', action: false, top: false },
  { icon: 'photo-o', name: '资金归集', to: '', type: 'wealth', action: false, top: false },
  { icon: 'photo-o', name: '信用卡还款', to: '', type: 'wealth', action: false, top: false },
  { icon: 'photo-o', name: '零花钱大作战', to: '', type: 'wealth', action: false, top: false },
  { icon: 'photo-o', name: '面对面红包', to: '', type: 'wealth', action: false, top: false },
  { icon: 'photo-o', name: '借钱', to: '', type: 'loan', action: false, top: false },
  { icon: 'photo-o', name: '我的贷款', to: '', type: 'loan', action: false, top: false },
  { icon: 'photo-o', name: '外汇购汇', to: '', type: 'finance', action: false, top: false },
  { icon: 'photo-o', name: '外汇结汇', to: '', type: 'finance', action: false, top: false },
  { icon: 'photo-o', name: '境外汇款', to: '', type: 'finance', action: false, top: false },
  { icon: 'photo-o', name: '外汇买卖', to: '', type: 'finance', action: false, top: false },
  { icon: 'photo-o', name: '国际IC卡', to: '', type: 'finance', action: false, top: false },
  { icon: 'photo-o', name: '代理签证', to: '', type: 'finance', action: false, top: false },
  { icon: 'photo-o', name: '国际汇入申报', to: '', type: 'finance', action: false, top: false },
];

export default {
  menus,
};
